### ISSUE TITLE
Invesitgate why sometimes when you click submit, it doesn't submit. (@CityofSantaMonica referred this)

### ISSUE THREAD

**Issue by eselkin** [hackla-engage/counciltaggame#1]

**Comment by matikin9** [comment]
I'm experiencing this as well.  I selected a few checkboxes, clicked Submit, and saw no response from the page.

**Comment by matikin9** [comment]
I checked the console and there's a Gateway Timeout error: 
![image](https://user-images.githubusercontent.com/1873072/38635541-8e739ddc-3d7a-11e8-9634-2755a75daebe.png)

**Comment by eselkin** [comment]
I'll put in something like an exponential backoff or something... I'll also put in a processing poup/modal

**Comment by matikin9** [comment]
Sounds good, some sort of indicator that things are working (or not working) as intended would be useful.

**Comment by eselkin** [comment]
Created exponential backoff and indicator it's trying to load
