### ISSUE TITLE
Upon login, text to evaluate is hidden

### ISSUE THREAD

**Issue by matikin9** [hackla-engage/counciltaggame#2]
It's not immediately clear what to do because the text to evaluate is hidden, and I have to click the title portion in order to view the text:

![image](https://user-images.githubusercontent.com/1873072/38635211-80a4fe36-3d79-11e8-95a7-e18f085b705f.png)

**Comment by eselkin** [comment]
This is because sometimes you may start out with something that has a LONG title (some are like a page long) and that would hide the actual submission area to start.

**Comment by eselkin** [comment]
I could probably test the length of the title and see if it's ok to expand... but on mobile it's probably never safe to start expanded

**Comment by owenjoseph** [comment]
@eselkin I'm going to move this to the "Future development" lane, given the tag game is not currently live.

**Comment by eselkin** [comment]
Take it off completely... not sure why it's even on there
