### ISSUE TITLE
Item with no text to evaluate

### ISSUE THREAD

**Issue by matikin9** [hackla-engage/counciltaggame#3]
Clicked the down arrow, no text appears for this item and there's no checkbox option for this situation.

![image](https://user-images.githubusercontent.com/1873072/38635325-da3f586a-3d79-11e8-896c-c5b73104e85a.png)

**Comment by eselkin** [comment]
Those actually have no content :-p That's not our problem it's a city problem.

**Comment by matikin9** [comment]
True, but could pose as a usability issue for your users.  Some sort of instructions indicating what to do if no  text appears could be useful, even if to distinguish between (a) items that have text but for which no tags apply and (b) items with no text thus no tags apply.

Actually, if there's no content - couldn't they be filtered out?  Or are some content-less items worth tagging based on the headline alone?

**Comment by eselkin** [comment]
Oh, that's weird, my statement about this didn't appear... or maybe I made it about your other issue :-p.. Some items have really really long titles and make the recommendations somewhat irrelevant for interpretation/labeling. But Yes, I will make something like ("looks like there's no recommendations here" info if there's nothing)
